cache:
  paths:
    - node_modules/
stages:
  - test

.npm:
  image: node
  before_script:
    - npm install

build:
  extends: .npm
  stage: test
  script:
    - npm run build

lint:
  extends: .npm
  stage: test
  script:
    - npm run lint
