cache:
  paths:
    - node_modules/
stages:
  - test

.npm:
  image: node
  before_script:
    - npm install -g gulp-cli
    - npm install

build:
  extends: .npm
  stage: test
  script:
    - gulp build

lint:
  extends: .npm
  stage: test
  script:
    - gulp lint
